--------------------------------------------------------------------------------
-- #267: Bad exception catching
--------------------------------------------------------------------------------

pcall inside xpcall:	true	pcall is ok
pcall with Lua error():	false	some message
pcall with box.error():	false	some message
pcall with box.error(): typeof	ctype<const struct error &>
pcall with box.error(): .type	IllegalParams
pcall with box.error(): .message	some message
pcall with box.error(): .match()	some
pcall with no return:	1
pcall with multireturn:	true	1	2	3
